import type {
  FestCompany,
  FestJobBooth,
  FestPromo,
  FestSideEvent,
  FestInterviewSlot,
  FestivalDatabase,
} from "./types";

// ─────────────────────────────────────────────────────────────
// 2026 김해 JOB FESTIVAL — 부스 시드 데이터
//
// ⚠️ 아래 기업/기관/프로그램은 화면·플로우 확인을 위한 **샘플 데이터**입니다.
//    실제 참가 확정 명단으로 교체해 주세요. (운영관리 → 부스 데이터)
// ─────────────────────────────────────────────────────────────

const c = (
  order: number,
  boothNo: string,
  name: string,
  industry: string,
  scale: string,
  logoText: string,
  summary: string,
  description: string,
  opts: Partial<FestCompany> & { positions: FestCompany["positions"] }
): FestCompany => ({
  id: `fc_${String(order).padStart(2, "0")}`,
  boothNo,
  name,
  industry,
  scale,
  location: "경남 김해시",
  employees: "50~299명",
  logoText,
  summary,
  description,
  products: [],
  welfare: ["4대보험", "연차/반차", "명절 상여", "중식 제공"],
  onSiteInterview: true,
  courses: ["job"],
  tags: [],
  featured: false,
  order,
  ...opts,
});

export const FEST_COMPANIES: FestCompany[] = [
  c(
    1,
    "A-01",
    "가야정밀공업(주)",
    "자동차부품",
    "중견기업",
    "가야",
    "완성차 3사에 공급하는 정밀 가공부품 전문기업",
    "1998년 김해에서 출발해 현재 국내 완성차 및 1차 협력사에 변속기·엔진 계열 정밀 가공부품을 공급합니다. 스마트팩토리 전환을 마치고 전동화(EV) 부품 라인을 신규 증설 중이며, 이에 따른 생산기술·품질 인력을 적극 채용합니다.",
    {
      employees: "300~499명",
      products: ["변속기 하우징", "EV 감속기 부품", "정밀 가공 모듈"],
      welfare: ["4대보험", "기숙사 운영", "자녀 학자금", "장기근속 포상", "통근버스"],
      homepage: "https://example.com",
      featured: true,
      tags: ["제조", "자동차", "기계", "생산관리", "품질", "EV"],
      courses: ["job", "career"],
      positions: [
        {
          id: "fp_01a",
          title: "생산관리",
          jobCategory: "fj_02",
          employmentType: "정규직",
          headcount: 3,
          experience: "신입/경력",
          salary: "3,200~3,800만원",
          requirements: ["기계·산업공학 계열 전공", "MS Office 활용 가능"],
          preferred: ["ERP 사용 경험", "품질경영기사 자격"],
        },
        {
          id: "fp_01b",
          title: "품질보증(QA)",
          jobCategory: "fj_03",
          employmentType: "정규직",
          headcount: 2,
          experience: "신입",
          salary: "3,000~3,400만원",
          requirements: ["측정기기 이해", "도면 해독 가능자"],
          preferred: ["IATF 16949 이해", "품질기사"],
        },
      ],
    }
  ),
  c(
    2,
    "A-02",
    "동원기계산업(주)",
    "기계·금속",
    "중소기업",
    "동원",
    "산업용 특수 유압장비 설계·제작 강소기업",
    "건설기계·조선 분야에 들어가는 유압 실린더와 파워유닛을 설계부터 제작까지 일괄 수행합니다. 설계 인력의 70%가 10년 이상 근속한 기술 중심 조직으로, 신입 사원에게 1:1 사수 제도를 운영합니다.",
    {
      products: ["유압 실린더", "파워유닛", "특수 장비 설계"],
      tags: ["기계", "설계", "제조", "CAD", "유압"],
      positions: [
        {
          id: "fp_02a",
          title: "기계설계",
          jobCategory: "fj_01",
          employmentType: "정규직",
          headcount: 2,
          experience: "신입/경력",
          salary: "3,000~4,000만원",
          requirements: ["기계공학 전공", "2D/3D CAD 사용 가능"],
          preferred: ["INVENTOR·CATIA 활용", "유압 회로 이해"],
        },
        {
          id: "fp_02b",
          title: "생산기술",
          jobCategory: "fj_02",
          employmentType: "정규직",
          headcount: 1,
          experience: "무관",
          requirements: ["현장 근무 가능자"],
          preferred: ["기계가공기능사 이상"],
        },
      ],
    }
  ),
  c(
    3,
    "A-03",
    "김해푸드테크(주)",
    "식품",
    "중견기업",
    "KFT",
    "대형 유통사 PB 간편식을 생산하는 HACCP 인증 식품기업",
    "냉장·냉동 간편식(HMR)을 개발·생산해 국내 대형 유통 3사에 공급합니다. 신제품 기획부터 생산까지 6개월 내 진행되는 빠른 사이클이 특징이며, 식품공학·조리·영양 전공자의 R&D 참여 기회가 많습니다.",
    {
      employees: "300~499명",
      products: ["냉장 간편식", "소스류", "HMR PB 제품"],
      welfare: ["4대보험", "사내식당", "제품 할인", "생일 휴가", "건강검진"],
      featured: true,
      tags: ["식품", "제조", "연구개발", "품질", "HACCP"],
      courses: ["job", "career"],
      positions: [
        {
          id: "fp_03a",
          title: "식품 연구개발",
          jobCategory: "fj_04",
          employmentType: "정규직",
          headcount: 2,
          experience: "신입",
          salary: "3,000~3,500만원",
          requirements: ["식품공학·조리·영양 관련 전공"],
          preferred: ["식품기사", "HMR 개발 경험"],
        },
        {
          id: "fp_03b",
          title: "품질관리(QC)",
          jobCategory: "fj_03",
          employmentType: "정규직",
          headcount: 3,
          experience: "신입",
          requirements: ["HACCP 이해", "교대 근무 가능"],
          preferred: ["식품산업기사"],
        },
        {
          id: "fp_03c",
          title: "영업관리",
          jobCategory: "fj_06",
          employmentType: "정규직",
          headcount: 2,
          experience: "무관",
          requirements: ["운전면허 1종 보통"],
          preferred: ["유통 영업 경험"],
        },
      ],
    }
  ),
  c(
    4,
    "A-04",
    "(주)메디바이오케어",
    "의료기기",
    "강소기업",
    "MBC",
    "정형외과용 의료기기 제조·수출 기업",
    "정형외과용 임플란트와 수술 기구를 생산해 20개국에 수출합니다. GMP·CE·FDA 인증을 보유하고 있으며 해외 인허가·품질 직무의 성장 기회가 큽니다.",
    {
      products: ["정형외과 임플란트", "수술 기구 세트"],
      welfare: ["4대보험", "해외 출장 기회", "자기계발비", "리프레시 휴가"],
      tags: ["의료기기", "바이오", "품질", "인허가", "수출", "해외영업"],
      positions: [
        {
          id: "fp_04a",
          title: "품질·인허가(RA)",
          jobCategory: "fj_03",
          employmentType: "정규직",
          headcount: 1,
          experience: "신입/경력",
          salary: "3,200~4,200만원",
          requirements: ["생명공학·의공학·화학 계열 전공", "영어 문서 독해 가능"],
          preferred: ["ISO 13485 이해", "의료기기 RA 경험"],
        },
        {
          id: "fp_04b",
          title: "해외영업",
          jobCategory: "fj_06",
          employmentType: "정규직",
          headcount: 1,
          experience: "무관",
          requirements: ["영어 회화 가능", "해외 출장 가능자"],
          preferred: ["무역영어", "제2외국어"],
        },
      ],
    }
  ),
  c(
    5,
    "A-05",
    "(주)스마트로직스",
    "물류·유통",
    "중견기업",
    "SLX",
    "부산신항 연계 스마트 물류센터 운영사",
    "부산신항과 김해 내륙물류기지를 잇는 통합 물류 서비스를 제공합니다. WMS/TMS 자체 개발 조직을 보유해 물류 운영직과 IT 개발직을 함께 채용합니다.",
    {
      employees: "500명 이상",
      products: ["3PL 물류 대행", "WMS 솔루션", "국제 운송"],
      welfare: ["4대보험", "주 5일", "교대수당", "자격 취득 지원"],
      tags: ["물류", "유통", "SCM", "IT", "운영관리"],
      courses: ["job", "career"],
      positions: [
        {
          id: "fp_05a",
          title: "물류 운영관리",
          jobCategory: "fj_07",
          employmentType: "정규직",
          headcount: 4,
          experience: "신입",
          salary: "3,000~3,600만원",
          requirements: ["엑셀 활용 가능", "교대 근무 가능"],
          preferred: ["물류관리사", "SCM 관련 전공"],
        },
        {
          id: "fp_05b",
          title: "백엔드 개발",
          jobCategory: "fj_05",
          employmentType: "정규직",
          headcount: 2,
          experience: "신입/경력",
          salary: "3,600~4,800만원",
          requirements: ["Java 또는 Python 개발 가능"],
          preferred: ["Spring Boot", "물류 도메인 이해"],
        },
      ],
    }
  ),
  c(
    6,
    "A-06",
    "(주)네오테크소프트",
    "IT·소프트웨어",
    "강소기업",
    "NTS",
    "제조 현장 특화 MES/스마트팩토리 솔루션 기업",
    "경남 제조기업 200여 곳에 MES(생산관리시스템)를 공급했습니다. 신입 개발자에게 3개월 부트캠프형 온보딩을 제공하며, 김해 테크노밸리 본사에서 근무합니다.",
    {
      employees: "50~299명",
      products: ["MES 솔루션", "설비 데이터 수집(IoT)", "품질 분석 대시보드"],
      welfare: ["4대보험", "유연근무제", "도서·교육비", "재택 주 1회"],
      featured: true,
      tags: ["IT", "개발", "소프트웨어", "데이터", "스마트팩토리"],
      courses: ["job", "career"],
      positions: [
        {
          id: "fp_06a",
          title: "웹 프론트엔드 개발",
          jobCategory: "fj_05",
          employmentType: "정규직",
          headcount: 2,
          experience: "신입",
          salary: "3,400~4,200만원",
          requirements: ["JavaScript 기본 이해", "포트폴리오 제출"],
          preferred: ["React 사용 경험", "부트캠프 수료"],
        },
        {
          id: "fp_06b",
          title: "데이터 분석",
          jobCategory: "fj_08",
          employmentType: "채용연계형 인턴",
          headcount: 2,
          experience: "신입",
          requirements: ["SQL 기본", "통계 기초 이해"],
          preferred: ["Python(pandas)", "제조 데이터 경험"],
        },
      ],
    }
  ),
  c(
    7,
    "A-07",
    "한백정밀화학(주)",
    "화학·소재",
    "중견기업",
    "한백",
    "2차전지·도료용 기능성 소재 제조기업",
    "2차전지 바인더와 산업용 도료 원료를 생산합니다. 안전·환경 관리 체계를 갖춘 스마트 화학공장으로, 화학공학 전공자의 공정기술 직무 성장 경로가 명확합니다.",
    {
      products: ["2차전지 바인더", "기능성 첨가제", "산업용 도료 원료"],
      welfare: ["4대보험", "교대수당", "사택 지원", "장기근속 포상"],
      tags: ["화학", "소재", "공정", "제조", "배터리"],
      positions: [
        {
          id: "fp_07a",
          title: "공정기술",
          jobCategory: "fj_02",
          employmentType: "정규직",
          headcount: 2,
          experience: "신입",
          salary: "3,400~4,000만원",
          requirements: ["화학공학·화학 전공"],
          preferred: ["화공기사", "위험물산업기사"],
        },
        {
          id: "fp_07b",
          title: "환경안전",
          jobCategory: "fj_09",
          employmentType: "정규직",
          headcount: 1,
          experience: "무관",
          requirements: ["안전 관련 법규 이해"],
          preferred: ["산업안전기사"],
        },
      ],
    }
  ),
  c(
    8,
    "A-08",
    "김해건설엔지니어링(주)",
    "건설·엔지니어링",
    "중소기업",
    "KCE",
    "지역 공공건축·토목 시공 및 감리 전문기업",
    "김해시 공공건축·도로 정비 사업을 다수 수행한 지역 대표 건설사입니다. 시공관리와 설계 지원 직무를 채용하며, 자격 취득 비용을 전액 지원합니다.",
    {
      products: ["공공건축 시공", "토목 정비", "건설사업관리(CM)"],
      welfare: ["4대보험", "자격수당", "현장수당", "명절 상여"],
      tags: ["건설", "토목", "건축", "시공", "안전"],
      positions: [
        {
          id: "fp_08a",
          title: "시공관리",
          jobCategory: "fj_10",
          employmentType: "정규직",
          headcount: 3,
          experience: "신입/경력",
          salary: "3,200~4,500만원",
          requirements: ["건축·토목공학 전공", "현장 근무 가능"],
          preferred: ["건축기사", "토목기사"],
        },
      ],
    }
  ),
  c(
    9,
    "A-09",
    "(주)에이스전장",
    "전기·전자",
    "중소기업",
    "ACE",
    "산업용 배전반·제어반 설계 제작 기업",
    "플랜트와 스마트팩토리 현장에 들어가는 배전반·자동제어반을 설계·제작합니다. 전기 계열 신입에게 설계-제작-시운전 전 과정을 경험시키는 순환 교육을 운영합니다.",
    {
      products: ["배전반", "자동제어반", "PLC 제어 시스템"],
      tags: ["전기", "전자", "제어", "설계", "PLC"],
      positions: [
        {
          id: "fp_09a",
          title: "전기제어 설계",
          jobCategory: "fj_01",
          employmentType: "정규직",
          headcount: 2,
          experience: "신입",
          salary: "3,000~3,800만원",
          requirements: ["전기·전자 계열 전공"],
          preferred: ["전기기사", "PLC 프로그래밍 경험"],
        },
      ],
    }
  ),
  c(
    10,
    "A-10",
    "(주)라온케어서비스",
    "보건·복지",
    "중견기업",
    "라온",
    "지역 요양·재활 서비스 운영 법인",
    "김해·창원 지역에서 노인요양시설과 주야간보호센터를 운영합니다. 사회복지·간호·작업치료 전공자를 대상으로 상시 채용하며, 직무 교육과 자격 지원이 체계적입니다.",
    {
      employees: "300~499명",
      products: ["노인요양시설", "주야간보호", "재가복지 서비스"],
      welfare: ["4대보험", "명절 상여", "복지포인트", "직무교육 지원"],
      tags: ["보건", "복지", "사회복지", "간호", "돌봄"],
      courses: ["job", "career"],
      positions: [
        {
          id: "fp_10a",
          title: "사회복지사",
          jobCategory: "fj_11",
          employmentType: "정규직",
          headcount: 4,
          experience: "무관",
          requirements: ["사회복지사 2급 이상"],
          preferred: ["요양시설 실습 경험"],
        },
        {
          id: "fp_10b",
          title: "간호(주간보호)",
          jobCategory: "fj_11",
          employmentType: "정규직",
          headcount: 2,
          experience: "무관",
          requirements: ["간호사 또는 간호조무사 자격"],
          preferred: ["노인복지 관련 경험"],
        },
      ],
    }
  ),
  c(
    11,
    "A-11",
    "(주)그린모빌리티부품",
    "자동차부품",
    "중소기업",
    "GMP",
    "전기차 열관리 부품 신규 진출 기업",
    "내연기관 부품에서 전기차 열관리 모듈로 사업을 전환하고 있는 성장 기업입니다. 신규 라인 셋업 인력과 개발 인력을 함께 뽑습니다.",
    {
      products: ["EV 열관리 모듈", "냉각 파이프", "정밀 프레스 부품"],
      tags: ["자동차", "제조", "EV", "생산관리", "개발"],
      positions: [
        {
          id: "fp_11a",
          title: "연구개발(설계)",
          jobCategory: "fj_01",
          employmentType: "정규직",
          headcount: 2,
          experience: "신입",
          salary: "3,200~3,900만원",
          requirements: ["기계·자동차공학 전공"],
          preferred: ["3D CAD", "열유동 해석 경험"],
        },
        {
          id: "fp_11b",
          title: "생산관리",
          jobCategory: "fj_02",
          employmentType: "정규직",
          headcount: 2,
          experience: "무관",
          requirements: ["제조 현장 근무 가능"],
          preferred: ["ERP/MES 사용 경험"],
        },
      ],
    }
  ),
  c(
    12,
    "A-12",
    "(주)해피리테일",
    "유통·서비스",
    "중견기업",
    "HR",
    "경남권 생활용품 유통·리테일 운영사",
    "경남 지역 40여 개 매장을 운영하며 온라인 자사몰을 함께 성장시키고 있습니다. MD·마케팅·매장운영 등 상경계열 직무 채용이 활발합니다.",
    {
      employees: "500명 이상",
      products: ["오프라인 매장 운영", "자사몰", "PB 상품 기획"],
      welfare: ["4대보험", "임직원 할인", "우수사원 포상", "정기 승진"],
      tags: ["유통", "마케팅", "MD", "서비스", "이커머스"],
      courses: ["job", "career"],
      positions: [
        {
          id: "fp_12a",
          title: "온라인 마케팅",
          jobCategory: "fj_12",
          employmentType: "정규직",
          headcount: 2,
          experience: "신입",
          salary: "2,900~3,400만원",
          requirements: ["SNS 콘텐츠 기획 관심자"],
          preferred: ["광고 집행 경험", "디자인 툴 활용"],
        },
        {
          id: "fp_12b",
          title: "MD(상품기획)",
          jobCategory: "fj_12",
          employmentType: "정규직",
          headcount: 1,
          experience: "신입/경력",
          requirements: ["엑셀 데이터 정리 가능"],
          preferred: ["리테일 근무 경험"],
        },
        {
          id: "fp_12c",
          title: "인사·총무",
          jobCategory: "fj_13",
          employmentType: "정규직",
          headcount: 1,
          experience: "신입",
          requirements: ["문서 작성 능력"],
          preferred: ["노무 관련 지식"],
        },
      ],
    }
  ),
];

export const FEST_JOBS: FestJobBooth[] = [
  {
    id: "fj_01",
    boothNo: "B-01",
    name: "설계·R&D",
    category: "연구·기술",
    summary: "제품의 구조와 성능을 도면과 데이터로 만드는 직무",
    description:
      "고객 요구사항과 기술 사양을 받아 제품 구조를 설계하고, 시제품 검증과 설계 변경을 통해 양산 가능한 형태로 완성하는 일을 합니다. 제조 도시 김해에서 가장 수요가 꾸준한 기술 직무입니다.",
    tasks: ["요구사양 분석", "2D/3D 도면 설계", "시제품 제작·검증", "설계 변경 및 표준화", "양산 이관"],
    skills: ["CAD 활용", "공학 기초(재료·역학)", "문제 정의력", "협업·문서화"],
    certificates: ["기계설계기사", "전기기사", "3D프린터운용기능사"],
    careerPath: ["설계 엔지니어", "선임 설계", "설계팀장 / PM", "기술연구소장"],
    salaryRange: "신입 3,000~3,800만원",
    outlook: "전동화·자동화 전환으로 설계 인력 수요 지속 증가",
    mentorTitle: "자동차부품사 설계 12년차 현직자",
    programs: ["도면 읽는 법 10분 특강", "설계 포트폴리오 첨삭", "현직자 1:1 상담"],
    relatedCompanyIds: ["fc_02", "fc_09", "fc_11"],
    tags: ["설계", "기계", "전기", "연구개발", "CAD"],
    order: 1,
  },
  {
    id: "fj_02",
    boothNo: "B-02",
    name: "생산·공정관리",
    category: "생산·기술",
    summary: "사람·설비·자재를 움직여 납기와 생산성을 만드는 직무",
    description:
      "생산 계획을 세우고 자재와 인력을 배분해 납기를 맞추며, 공정 데이터를 분석해 불량과 낭비를 줄입니다. 제조기업 취업의 가장 큰 관문이자 현장 이해도가 빠르게 쌓이는 직무입니다.",
    tasks: ["생산계획 수립", "자재 소요 관리(MRP)", "공정 개선", "설비 가동률 관리", "현장 이슈 대응"],
    skills: ["엑셀·데이터 정리", "ERP/MES 이해", "커뮤니케이션", "공정 흐름 이해"],
    certificates: ["품질경영기사", "산업안전기사", "생산자동화산업기사"],
    careerPath: ["생산관리 담당", "공정 개선 리더", "생산팀장", "공장장"],
    salaryRange: "신입 2,900~3,600만원",
    outlook: "스마트팩토리 확산으로 데이터 기반 생산관리 인력 선호",
    mentorTitle: "제조 대기업 생산관리 9년차 현직자",
    programs: ["생산관리 하루 일과 소개", "제조 취업 자소서 클리닉", "현직자 1:1 상담"],
    relatedCompanyIds: ["fc_01", "fc_07", "fc_11"],
    tags: ["생산관리", "제조", "공정", "품질", "현장"],
    order: 2,
  },
  {
    id: "fj_03",
    boothNo: "B-03",
    name: "품질관리·품질보증",
    category: "생산·기술",
    summary: "제품이 기준을 지키게 만드는 검사·시스템 직무",
    description:
      "입고부터 출하까지 품질 기준을 정의하고 검사·측정으로 이를 확인하며, 불량이 재발하지 않도록 시스템(문서·프로세스)을 관리합니다. QC(검사)와 QA(시스템)로 나뉩니다.",
    tasks: ["수입/공정/출하 검사", "측정 데이터 분석", "부적합 처리 및 개선", "품질 문서 관리", "고객 감사 대응"],
    skills: ["측정기기 사용", "통계적 품질관리(SPC)", "문서 작성", "꼼꼼함"],
    certificates: ["품질경영기사", "식품기사", "비파괴검사기사"],
    careerPath: ["QC 담당", "QA 담당", "품질팀장", "품질경영 총괄"],
    salaryRange: "신입 2,800~3,500만원",
    outlook: "완성차·의료기기·식품 등 인증 요구 강화로 안정적 수요",
    mentorTitle: "의료기기 품질보증 7년차 현직자",
    programs: ["측정기 체험", "품질 직무 적합도 진단", "현직자 1:1 상담"],
    relatedCompanyIds: ["fc_01", "fc_03", "fc_04"],
    tags: ["품질", "검사", "QA", "QC", "인증"],
    order: 3,
  },
  {
    id: "fj_04",
    boothNo: "B-04",
    name: "식품 연구개발",
    category: "연구·기술",
    summary: "먹는 제품을 기획하고 배합을 완성하는 직무",
    description:
      "시장 트렌드를 반영한 신제품을 기획하고, 배합·공정 조건을 설계해 관능 평가와 유통기한 검증을 거쳐 양산으로 연결합니다. 식품 도시 김해의 대표 직무 중 하나입니다.",
    tasks: ["신제품 컨셉 기획", "배합 설계·시제품 제작", "관능 평가", "유통기한 검증", "양산 스케일업"],
    skills: ["식품화학 기초", "위생·HACCP 이해", "기록·보고", "미각·관능 감각"],
    certificates: ["식품기사", "영양사", "조리기능사"],
    careerPath: ["연구원", "선임연구원", "제품개발 PM", "연구소장"],
    salaryRange: "신입 2,900~3,500만원",
    outlook: "간편식(HMR)·건강기능식품 성장으로 개발 인력 확대",
    mentorTitle: "간편식 제조사 R&D 6년차 현직자",
    programs: ["신제품 기획 미니 워크숍", "관능평가 체험", "현직자 1:1 상담"],
    relatedCompanyIds: ["fc_03"],
    tags: ["식품", "연구개발", "HACCP", "제품기획"],
    order: 4,
  },
  {
    id: "fj_05",
    boothNo: "B-05",
    name: "소프트웨어 개발",
    category: "IT·디지털",
    summary: "서비스와 시스템을 코드로 만드는 직무",
    description:
      "웹·앱 서비스나 기업 내부 시스템을 설계하고 구현합니다. 지역 IT 기업은 제조 도메인(MES·물류)에 특화된 경우가 많아, 도메인 이해가 있는 개발자가 빠르게 성장합니다.",
    tasks: ["요구사항 분석", "화면·API 개발", "테스트 및 배포", "장애 대응", "성능 개선"],
    skills: ["프로그래밍 언어 1개 이상", "데이터베이스(SQL)", "Git 협업", "논리적 사고"],
    certificates: ["정보처리기사", "SQLD", "리눅스마스터"],
    careerPath: ["주니어 개발자", "시니어 개발자", "테크리드", "CTO / 창업"],
    salaryRange: "신입 3,200~4,200만원",
    outlook: "제조 DX 수요로 지역 IT 채용 지속 확대",
    mentorTitle: "스마트팩토리 솔루션사 개발 8년차 현직자",
    programs: ["포트폴리오 코드 리뷰", "비전공자 개발 진입 상담", "현직자 1:1 상담"],
    relatedCompanyIds: ["fc_05", "fc_06"],
    tags: ["IT", "개발", "프로그래밍", "웹", "소프트웨어"],
    order: 5,
  },
  {
    id: "fj_06",
    boothNo: "B-06",
    name: "영업·해외영업",
    category: "경영·사무",
    summary: "제품과 고객을 연결해 매출을 만드는 직무",
    description:
      "고객사를 발굴하고 제안·견적·계약을 진행하며, 납품 이후 관계 관리까지 담당합니다. 해외영업은 바이어 발굴과 수출 실무(무역·인코텀즈)를 함께 수행합니다.",
    tasks: ["고객 발굴 및 제안", "견적·단가 협의", "수주 관리", "클레임 대응", "시장 조사"],
    skills: ["커뮤니케이션", "제품 이해력", "협상력", "외국어(해외영업)"],
    certificates: ["무역영어", "국제무역사", "컴퓨터활용능력"],
    careerPath: ["영업 담당", "키어카운트 매니저", "영업팀장", "사업부장"],
    salaryRange: "신입 2,800~3,600만원 (+인센티브)",
    outlook: "수출 중심 강소기업의 해외영업 수요 꾸준",
    mentorTitle: "의료기기 해외영업 10년차 현직자",
    programs: ["영업 롤플레이 체험", "무역 실무 미니 특강", "현직자 1:1 상담"],
    relatedCompanyIds: ["fc_03", "fc_04"],
    tags: ["영업", "해외영업", "무역", "상경", "고객"],
    order: 6,
  },
  {
    id: "fj_07",
    boothNo: "B-07",
    name: "물류·SCM",
    category: "경영·사무",
    summary: "재고와 운송을 설계해 비용과 시간을 줄이는 직무",
    description:
      "입출고와 재고를 관리하고 운송 경로·비용을 최적화합니다. 부산신항과 인접한 김해는 물류 직무 채용이 특히 활발한 지역입니다.",
    tasks: ["입출고 관리", "재고 정확도 관리", "배차·운송 관리", "물류비 분석", "창고 운영 개선"],
    skills: ["엑셀 데이터 분석", "WMS 이해", "현장 커뮤니케이션", "수리적 사고"],
    certificates: ["물류관리사", "유통관리사", "지게차운전기능사"],
    careerPath: ["물류 운영", "SCM 기획", "물류센터장", "SCM 총괄"],
    salaryRange: "신입 2,900~3,600만원",
    outlook: "이커머스·수출입 물동량 증가로 지속 성장",
    mentorTitle: "3PL 물류센터 운영 11년차 현직자",
    programs: ["물류센터 운영 시뮬레이션", "물류관리사 준비 상담", "현직자 1:1 상담"],
    relatedCompanyIds: ["fc_05", "fc_12"],
    tags: ["물류", "SCM", "재고", "운송", "유통"],
    order: 7,
  },
  {
    id: "fj_08",
    boothNo: "B-08",
    name: "데이터 분석",
    category: "IT·디지털",
    summary: "데이터로 현상을 설명하고 의사결정을 돕는 직무",
    description:
      "생산·판매·고객 데이터를 수집·정제해 지표를 만들고, 문제 원인을 찾아 개선안을 제시합니다. 제조 데이터 분석은 지역 기업에서 수요가 빠르게 늘고 있습니다.",
    tasks: ["데이터 수집·정제", "지표 설계 및 대시보드 구축", "원인 분석", "예측 모델링", "결과 리포팅"],
    skills: ["SQL", "Python/R", "통계 기초", "시각화·전달력"],
    certificates: ["ADsP / ADP", "SQLD", "빅데이터분석기사"],
    careerPath: ["데이터 분석가", "데이터 사이언티스트", "분석팀 리드", "CDO"],
    salaryRange: "신입 3,200~4,000만원",
    outlook: "스마트팩토리·이커머스 확산으로 수요 증가",
    mentorTitle: "제조 데이터 분석 6년차 현직자",
    programs: ["데이터 직무 로드맵 상담", "분석 포트폴리오 리뷰", "현직자 1:1 상담"],
    relatedCompanyIds: ["fc_06", "fc_05"],
    tags: ["데이터", "분석", "IT", "통계", "AI"],
    order: 8,
  },
  {
    id: "fj_09",
    boothNo: "B-09",
    name: "환경·안전(EHS)",
    category: "생산·기술",
    summary: "사람이 다치지 않고 규제를 지키게 만드는 직무",
    description:
      "위험성 평가와 안전 교육, 환경 배출 관리와 법정 인허가를 담당합니다. 중대재해처벌법 시행 이후 기업들의 채용이 크게 늘어난 직무입니다.",
    tasks: ["위험성 평가", "안전 교육·점검", "환경 배출 관리", "법정 인허가·보고", "사고 조사"],
    skills: ["안전보건 법규 이해", "현장 점검력", "문서 작성", "설득·교육 역량"],
    certificates: ["산업안전기사", "환경기사", "위험물산업기사"],
    careerPath: ["EHS 담당", "안전관리자(선임)", "EHS 팀장", "ESG 총괄"],
    salaryRange: "신입 3,000~3,800만원",
    outlook: "법 강화로 전 산업에서 채용 확대, 자격 보유 시 유리",
    mentorTitle: "화학기업 EHS 9년차 현직자",
    programs: ["안전자격 취득 로드맵", "EHS 직무 상담", "현직자 1:1 상담"],
    relatedCompanyIds: ["fc_07", "fc_08"],
    tags: ["안전", "환경", "EHS", "자격", "규제"],
    order: 9,
  },
  {
    id: "fj_10",
    boothNo: "B-10",
    name: "건설·시공관리",
    category: "생산·기술",
    summary: "설계도를 실제 건축물로 만드는 현장 관리 직무",
    description:
      "공정·품질·안전·원가를 관리하며 현장을 운영합니다. 자격 취득에 따른 보상이 명확하고, 경력에 따라 소장으로 성장하는 경로가 뚜렷합니다.",
    tasks: ["공정표 관리", "협력업체 관리", "품질·안전 점검", "기성·원가 관리", "발주처 협의"],
    skills: ["도면 해독", "현장 소통", "일정 관리", "체력·책임감"],
    certificates: ["건축기사", "토목기사", "건설안전기사"],
    careerPath: ["공사 담당", "공무/공사 과장", "현장소장", "임원"],
    salaryRange: "신입 3,200~4,000만원 (+현장수당)",
    outlook: "지역 공공사업·도시재생 물량 꾸준",
    mentorTitle: "지역 건설사 현장소장 15년차 현직자",
    programs: ["현장직 근무환경 Q&A", "건설 자격 준비 상담", "현직자 1:1 상담"],
    relatedCompanyIds: ["fc_08"],
    tags: ["건설", "시공", "토목", "건축", "현장"],
    order: 10,
  },
  {
    id: "fj_11",
    boothNo: "B-11",
    name: "사회복지·보건",
    category: "보건·복지",
    summary: "돌봄과 복지 서비스를 설계하고 제공하는 직무",
    description:
      "대상자 상담과 사례 관리, 프로그램 기획·운영, 자원 연계를 수행합니다. 고령화가 빠른 지역 특성상 채용이 안정적으로 유지됩니다.",
    tasks: ["초기 상담·사정", "사례 관리", "프로그램 기획·운영", "지역 자원 연계", "행정 서류 관리"],
    skills: ["상담·공감 능력", "기록·문서화", "프로그램 기획", "위기 대응"],
    certificates: ["사회복지사 1·2급", "요양보호사", "간호조무사"],
    careerPath: ["생활지원·복지 담당", "선임 사회복지사", "시설 팀장", "센터장"],
    salaryRange: "신입 2,700~3,300만원",
    outlook: "고령화·돌봄 수요 증가로 지속 확대",
    mentorTitle: "노인복지시설 사회복지사 8년차 현직자",
    programs: ["복지 현장 실무 Q&A", "실습·자격 상담", "현직자 1:1 상담"],
    relatedCompanyIds: ["fc_10"],
    tags: ["복지", "보건", "상담", "돌봄", "사회복지"],
    order: 11,
  },
  {
    id: "fj_12",
    boothNo: "B-12",
    name: "마케팅·MD",
    category: "경영·사무",
    summary: "상품과 브랜드를 고객에게 닿게 만드는 직무",
    description:
      "시장과 고객을 분석해 상품을 기획하고, 콘텐츠·광고·프로모션으로 판매를 만듭니다. 온라인 채널 운영 경험이 있으면 진입이 빠릅니다.",
    tasks: ["시장·경쟁 분석", "상품 기획(MD)", "콘텐츠 제작", "광고 집행·성과 분석", "프로모션 운영"],
    skills: ["콘텐츠 기획", "데이터 해석", "디자인 툴 기초", "트렌드 감각"],
    certificates: ["GAIQ", "SNS광고마케터", "컴퓨터활용능력"],
    careerPath: ["마케터 / MD", "브랜드 매니저", "마케팅팀장", "CMO"],
    salaryRange: "신입 2,700~3,300만원",
    outlook: "이커머스 확대로 실무형 인재 선호",
    mentorTitle: "리테일 마케팅 7년차 현직자",
    programs: ["SNS 콘텐츠 실습", "마케팅 포트폴리오 첨삭", "현직자 1:1 상담"],
    relatedCompanyIds: ["fc_12"],
    tags: ["마케팅", "MD", "브랜드", "이커머스", "콘텐츠"],
    order: 12,
  },
  {
    id: "fj_13",
    boothNo: "B-13",
    name: "인사·총무",
    category: "경영·사무",
    summary: "사람과 조직이 돌아가게 만드는 관리 직무",
    description:
      "채용부터 근태·급여·교육·평가까지 조직 운영 전반을 담당합니다. 중소·중견기업에서는 인사와 총무를 함께 수행하는 경우가 많아 업무 범위가 넓습니다.",
    tasks: ["채용 기획·진행", "근태·급여 관리", "교육 운영", "평가·보상 지원", "사내 행사·자산 관리"],
    skills: ["노동관계법 기초", "문서·데이터 관리", "커뮤니케이션", "보안 의식"],
    certificates: ["경영지도사", "공인노무사", "컴퓨터활용능력"],
    careerPath: ["인사 담당", "HRM/HRD 전문", "인사팀장", "경영지원 총괄"],
    salaryRange: "신입 2,700~3,200만원",
    outlook: "인사 데이터·노무 리스크 관리 역량 요구 증가",
    mentorTitle: "중견 제조사 인사 10년차 현직자",
    programs: ["면접관이 보는 이력서", "인사 직무 진입 상담", "현직자 1:1 상담"],
    relatedCompanyIds: ["fc_12"],
    tags: ["인사", "총무", "HR", "노무", "경영지원"],
    order: 13,
  },
];

export const FEST_PROMOS: FestPromo[] = [
  {
    id: "fpr_01",
    boothNo: "C-01",
    name: "김해시 일자리종합센터",
    category: "공공기관",
    summary: "김해시민 대상 취업 상담·알선 원스톱 창구",
    description:
      "구직 등록부터 상담, 일자리 알선, 취업 후 사후관리까지 연결하는 김해시 대표 취업지원 창구입니다. 축제 당일 등록하면 이후 맞춤 일자리 정보를 문자로 받아볼 수 있습니다.",
    services: ["1:1 취업 상담", "구인·구직 매칭", "취업성공수당 안내", "이력서 등록 지원"],
    targets: ["김해시 거주 구직자", "졸업예정자", "경력단절자"],
    contact: "055-000-0000",
    tags: ["취업지원", "상담", "공공"],
    order: 1,
  },
  {
    id: "fpr_02",
    boothNo: "C-02",
    name: "김해시 청년드림 지원단",
    category: "정책",
    summary: "청년 정착·자립을 돕는 김해시 청년정책 안내",
    description:
      "청년 주거·자산형성·문화활동 등 김해시 청년정책을 한자리에서 안내합니다. 신청 자격 진단표를 통해 내가 받을 수 있는 사업을 즉시 확인할 수 있습니다.",
    services: ["청년정책 자격 진단", "청년 주거·자산형성 안내", "청년공간 이용 안내"],
    targets: ["만 19~39세 김해시 청년"],
    tags: ["청년정책", "주거", "지원금", "공공"],
    order: 2,
  },
  {
    id: "fpr_03",
    boothNo: "C-03",
    name: "인제대학교 대학일자리플러스센터",
    category: "대학",
    summary: "재학생·졸업생 진로설계와 취업역량 프로그램",
    description:
      "진로 심리검사, 직무 캠프, 채용 연계 프로그램을 운영합니다. 타 대학 재학생도 참여 가능한 공동 프로그램을 안내합니다.",
    services: ["진로·직업 심리검사", "취업 캠프 안내", "졸업생 취업 상담"],
    targets: ["재학생", "졸업생", "지역 청년"],
    tags: ["대학", "진로", "역량강화"],
    order: 3,
  },
  {
    id: "fpr_04",
    boothNo: "C-04",
    name: "가야대학교 취업지원센터",
    category: "대학",
    summary: "보건·복지 특화 진로 상담 및 자격 안내",
    description:
      "보건·복지·간호 계열 진로 로드맵과 현장실습, 자격 취득 지원 프로그램을 안내합니다.",
    services: ["계열별 진로 상담", "현장실습 연계", "자격 취득 로드맵"],
    targets: ["재학생", "졸업생", "전과·편입 고민 학생"],
    tags: ["대학", "보건복지", "자격"],
    order: 4,
  },
  {
    id: "fpr_05",
    boothNo: "C-05",
    name: "영산대학교 현장실습지원센터",
    category: "대학",
    summary: "기업 연계 현장실습·인턴십 매칭",
    description:
      "학기제·방학제 현장실습과 채용연계형 인턴십 기업 풀을 안내하고, 참여 절차와 학점 인정 기준을 상담합니다.",
    services: ["현장실습 기업 매칭", "인턴십 상담", "학점 인정 안내"],
    targets: ["재학생 2~4학년"],
    tags: ["대학", "인턴십", "현장실습"],
    order: 5,
  },
  {
    id: "fpr_06",
    boothNo: "C-06",
    name: "김해대학교 직업교육혁신센터",
    category: "대학",
    summary: "직무 중심 단기 교육과정 및 재직자 과정 안내",
    description:
      "산업 수요에 맞춘 단기 직무 과정과 재직자 향상 과정을 안내합니다. 비전공자 대상 입문 과정도 운영합니다.",
    services: ["단기 직무과정 안내", "재직자 교육 상담", "직업교육 학위 과정"],
    targets: ["구직자", "재직자", "전공 전환 희망자"],
    tags: ["대학", "직업교육", "재직자"],
    order: 6,
  },
  {
    id: "fpr_07",
    boothNo: "C-07",
    name: "경남경영자총협회 / 지역 기업지원기관",
    category: "취업지원",
    summary: "지역 기업 채용 정보와 산업별 인력 수요 안내",
    description:
      "경남 지역 기업의 채용 계획과 산업별 인력 수요 동향을 안내하고, 기업이 실제로 원하는 인재상을 설명합니다.",
    services: ["산업별 채용 동향 안내", "기업 인재상 브리핑", "지역 기업 정보 제공"],
    targets: ["구직자", "진로 탐색 학생"],
    tags: ["기업지원", "채용정보", "산업동향"],
    order: 7,
  },
  {
    id: "fpr_08",
    boothNo: "C-08",
    name: "고용노동부 국민취업지원제도 안내",
    category: "공공기관",
    summary: "구직촉진수당 및 취업지원 서비스 안내",
    description:
      "국민취업지원제도 1·2유형 신청 자격과 절차, 구직촉진수당과 취업활동계획 수립 과정을 안내합니다.",
    services: ["유형별 자격 진단", "신청 절차 안내", "취업활동계획 상담"],
    targets: ["미취업 청년", "저소득 구직자"],
    tags: ["공공", "취업지원", "수당"],
    order: 8,
  },
  {
    id: "fpr_09",
    boothNo: "C-09",
    name: "김해 창업지원센터",
    category: "창업",
    summary: "예비창업자 대상 자금·공간·멘토링 안내",
    description:
      "예비창업패키지, 창업보육공간, 창업 멘토링 등 지역 창업 지원사업을 안내합니다. 아이디어 단계 상담도 가능합니다.",
    services: ["창업 지원사업 안내", "보육공간 입주 상담", "창업 멘토링 연결"],
    targets: ["예비창업자", "3년 이내 초기창업자"],
    tags: ["창업", "지원사업", "멘토링"],
    order: 9,
  },
  {
    id: "fpr_10",
    boothNo: "C-10",
    name: "여성새로일하기센터 / 중장년 일자리",
    category: "취업지원",
    summary: "경력단절 여성·중장년 재취업 지원",
    description:
      "경력단절 여성과 중장년 구직자를 위한 직업훈련, 인턴십, 재취업 상담을 제공합니다.",
    services: ["재취업 상담", "직업훈련 과정 안내", "새일 인턴십 연계"],
    targets: ["경력단절 여성", "40세 이상 중장년 구직자"],
    tags: ["재취업", "여성", "중장년"],
    order: 10,
  },
];

export const FEST_EVENTS: FestSideEvent[] = [
  {
    id: "fe_01",
    boothNo: "D-01",
    title: "무료 이력서 사진 촬영",
    category: "체험",
    place: "부대행사존 D-01",
    summary: "전문 작가가 찍어주는 증명·이력서 사진 (당일 파일 제공)",
    description:
      "정장 대여와 간단한 스타일링 후 전문 작가가 촬영합니다. 보정본은 당일 문자로 전송되며, 이력서에 바로 사용할 수 있습니다.",
    timeSlots: ["10:00-12:30", "13:30-17:00"],
    capacity: 200,
    needReserve: true,
    notes: ["상의 정장 대여 가능", "1인 1회", "대기 시 QR 순번 안내"],
    courses: ["job", "career"],
    tags: ["사진", "이력서", "무료"],
    order: 1,
  },
  {
    id: "fe_02",
    boothNo: "D-02",
    title: "1:1 이력서·자기소개서 컨설팅",
    category: "컨설팅",
    place: "부대행사존 D-02",
    summary: "현직 인사담당자와 20분 밀착 첨삭",
    description:
      "작성해 온 이력서·자소서를 인사담당자가 직접 첨삭합니다. 사전 업로드한 지원서가 있으면 우선 배정됩니다.",
    timeSlots: ["10:00-12:00", "13:00-17:00"],
    capacity: 80,
    needReserve: true,
    notes: ["1인 20분", "이력서 지참 권장", "사전등록자 우선"],
    courses: ["job"],
    tags: ["컨설팅", "이력서", "자소서", "인사담당자"],
    order: 2,
  },
  {
    id: "fe_03",
    boothNo: "D-03",
    title: "AI 모의면접 체험",
    category: "체험",
    place: "부대행사존 D-03",
    summary: "AI가 분석하는 표정·목소리·답변 피드백 리포트",
    description:
      "실제 면접과 유사한 질문에 답하면 AI가 표정·시선·음성·답변 구조를 분석해 리포트를 제공합니다. 결과는 마이페이지에서 다시 확인할 수 있습니다.",
    timeSlots: ["10:00-17:00"],
    capacity: 120,
    needReserve: true,
    notes: ["1회 15분", "헤드셋 제공", "결과 리포트 메일 발송"],
    courses: ["job", "career"],
    tags: ["면접", "AI", "체험"],
    order: 3,
  },
  {
    id: "fe_04",
    boothNo: "D-04",
    title: "직업심리검사 & 진로 상담",
    category: "상담",
    place: "부대행사존 D-04",
    summary: "검사 후 전문 상담사와 결과 해석 상담",
    description:
      "직업선호도·직업가치관 검사를 현장에서 진행하고, 전문 상담사가 결과를 해석해 진로 방향을 함께 정리합니다.",
    timeSlots: ["10:00-16:30"],
    capacity: 100,
    needReserve: false,
    notes: ["검사 20분 + 상담 15분", "Career 코스 추천"],
    courses: ["career"],
    tags: ["진로", "심리검사", "상담"],
    order: 4,
  },
  {
    id: "fe_05",
    boothNo: "D-05",
    title: "취업 특강 — 지역 기업이 원하는 인재",
    category: "특강",
    place: "메인 스테이지",
    summary: "인사담당자 3인이 말하는 서류·면접 합격 기준",
    description:
      "지역 중견·강소기업 인사담당자가 직접 서류 평가 기준과 면접 평가 포인트를 공개합니다. 강연 후 현장 질의응답이 이어집니다.",
    timeSlots: ["11:00-11:50", "15:00-15:50"],
    capacity: 150,
    needReserve: false,
    notes: ["선착순 입장", "강연자료 QR 배포"],
    courses: ["job", "career"],
    tags: ["특강", "면접", "인사담당자"],
    order: 5,
  },
  {
    id: "fe_06",
    boothNo: "D-06",
    title: "스탬프 랠리 & 경품 추첨",
    category: "이벤트",
    place: "종합안내부스",
    summary: "4개 관 스탬프 완주 시 경품 응모 + 기념품 증정",
    description:
      "기업관·직무관·홍보관·부대행사 각 1회 이상 참여하면 스탬프가 자동 적립됩니다. 4개를 모두 모으면 완주 코드가 발급되고, 종합안내부스에서 기념품과 경품 응모권을 받을 수 있습니다.",
    timeSlots: ["10:00-16:30"],
    capacity: 0,
    needReserve: false,
    notes: ["입장 QR 기준 자동 적립", "경품 추첨 16:40 메인 스테이지", "본인 확인 필요"],
    courses: ["job", "career"],
    tags: ["스탬프", "경품", "이벤트"],
    order: 6,
  },
  {
    id: "fe_07",
    boothNo: "D-07",
    title: "퍼스널 컬러 & 면접 이미지 메이킹",
    category: "체험",
    place: "부대행사존 D-07",
    summary: "면접에 어울리는 컬러·스타일 진단",
    description:
      "퍼스널 컬러 진단과 함께 면접 상황에 맞는 복장·헤어 스타일링 팁을 제공합니다.",
    timeSlots: ["10:30-16:00"],
    capacity: 90,
    needReserve: false,
    notes: ["1인 10분", "현장 대기 순번제"],
    courses: ["job", "career"],
    tags: ["이미지", "퍼스널컬러", "면접"],
    order: 7,
  },
  {
    id: "fe_08",
    boothNo: "D-08",
    title: "청년 창업 아이디어 상담존",
    category: "상담",
    place: "부대행사존 D-08",
    summary: "아이디어 단계부터 받는 창업 멘토링",
    description:
      "창업 선배와 지원기관 담당자가 아이디어 검증, 사업계획서 작성, 지원사업 신청 방법을 상담합니다.",
    timeSlots: ["10:00-16:00"],
    capacity: 40,
    needReserve: false,
    notes: ["1인 20분", "사업계획서 지참 시 심화 상담"],
    courses: ["career"],
    tags: ["창업", "멘토링", "상담"],
    order: 8,
  },
  {
    id: "fe_09",
    boothNo: "D-09",
    title: "청년 문화 공연 & 버스킹",
    category: "공연",
    place: "메인 스테이지",
    summary: "지역 청년 아티스트 무대와 참여 이벤트",
    description:
      "지역 대학 동아리와 청년 아티스트가 꾸미는 공연 무대입니다. 중간중간 참여 이벤트와 경품 추첨이 진행됩니다.",
    timeSlots: ["12:00-13:00", "16:00-17:00"],
    capacity: 0,
    needReserve: false,
    notes: ["자유 관람"],
    courses: ["job", "career"],
    tags: ["공연", "문화", "버스킹"],
    order: 9,
  },
  {
    id: "fe_10",
    boothNo: "D-10",
    title: "푸드트럭 & 휴식존",
    category: "이벤트",
    place: "야외 휴식존",
    summary: "간단한 식음료와 휴식 공간",
    description: "행사 참여 중 쉬어갈 수 있는 야외 휴식존과 푸드트럭이 운영됩니다.",
    timeSlots: ["10:00-17:00"],
    capacity: 0,
    needReserve: false,
    notes: ["일부 유료", "쓰레기 분리 배출 협조"],
    courses: ["job", "career"],
    tags: ["휴식", "푸드트럭"],
    order: 10,
  },
];

/** 기업별 현장 면접 슬롯 (11:00~16:30, 30분 단위 / 점심시간 제외) */
export function buildInterviewSlots(): FestInterviewSlot[] {
  const times = [
    "11:00",
    "11:30",
    "13:00",
    "13:30",
    "14:00",
    "14:30",
    "15:00",
    "15:30",
    "16:00",
    "16:30",
  ];
  const slots: FestInterviewSlot[] = [];
  for (const company of FEST_COMPANIES) {
    if (!company.onSiteInterview) continue;
    times.forEach((time, i) => {
      slots.push({
        id: `fs_${company.id}_${time.replace(":", "")}`,
        companyId: company.id,
        time,
        durationMin: 25,
        capacity: 2,
        place: `기업관 ${company.boothNo} 면접석 ${(i % 2) + 1}`,
      });
    });
  }
  return slots;
}

export function buildFestivalSeed(): FestivalDatabase {
  return {
    festCompanies: FEST_COMPANIES,
    festJobs: FEST_JOBS,
    festPromos: FEST_PROMOS,
    festEvents: FEST_EVENTS,
    festVisitors: [],
    festCheckins: [],
    festApplications: [],
    festInterviewSlots: buildInterviewSlots(),
    festInterviews: [],
    festStamps: [],
    festSurveys: [],
  };
}
